#! /bin/bash
set -e
echo "---------------------------------------"
echo "|  postinst args: [$*]-c($#)         "
echo "---------------------------------------"

echo "getting tmp file ..."
tFile=`mktemp`


#get nodes
# curl -X GET -H "Content-Type: application/json" -H "Accept: application/json" "http://localhost:1880/nodes/"


echo "* checking if Node-red is ok ..."
/data/data/com.termux/files/usr/bin/otdmTools.py -dnrfByUid '*' -oFile ${tFile} > /dev/null
isF=`cat ${tFile} | jq '.[] | select( .label == "ySS" )' | grep '{' > /dev/null; echo $?`
if [ ${isF} = "1" ]
then

  echo "* replacing paths..."
  #sea='msg.bPath = \"/home/yoyo/Apps/oiyshTerminal/ySS_calibration/\";'
  #rep='msg.bPath = \"/data/data/com.termux/files/home/.otdm/yss/\";'
  sed -i "s|/home/yoyo/Apps/oiyshTerminal/ySS_calibration/|/data/data/com.termux/files/home/.otdm/yss/|g" /data/data/com.termux/files/home/.otdm/nrf-yss/nrf_org.json

  echo "* first lets make a backup of Node-red...."
  /data/data/com.termux/files/usr/bin/otdmTools.py -mkbp flows -bSuffix 'beforeInjecting_nrf-yss' > /dev/null

  echo "* injecting it...."
  /data/data/com.termux/files/usr/bin/otdmTools.py \
  -dnrfByUid 1 \
  -act POST \
  -iFile /data/data/com.termux/files/home/.otdm/nrf-yss/nrf_org.json > /dev/null

else
  echo " E!E - there is flow with 'ySS' name in your Node-red. It's not a clean start.
  So you can import it manually.
  Injection / import file is in .otdm/nrf-yss/flow_xx.json"

fi

echo " done "
